newIssueWelcomeComment: >
  Thanks for your contribution in creating this hydrate-reminder issue!
  ![https://media.giphy.com/media/eng1F85OwyqQe6JHc2/giphy.gif](https://media.giphy.com/media/eng1F85OwyqQe6JHc2/giphy.gif)

newPRWelcomeComment: >
  Thanks for opening this pull request for hydrate-reminder! Please wait shortly for someone to review.
  ![https://media.giphy.com/media/JVBV02JFVmWrut9H8j/giphy.gif](https://media.giphy.com/media/JVBV02JFVmWrut9H8j/giphy.gif)

firstPRMergeComment: >
  Congrats on merging your first pull request to hydrate-reminder!
  ![https://media.giphy.com/media/6RbEFpsxCOVOBUoJc4/giphy.gif](https://media.giphy.com/media/6RbEFpsxCOVOBUoJc4/giphy.gif)
  
sentimentBotToxicityThreshold: .7

sentimentBotReplyComment: >
  Please be sure to review the code of conduct and be respectful of other users. cc/ @jmakhack
