name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Looks like this is your first submitted issue to hydrate-reminder. Thanks for the submission!'
        pr-message: 'Congrats on your first PR to this project and thank you for your contribution!'
